### ISSUE TITLE
I get command not found error with some commands

### ISSUE THREAD

**Issue by fedescarpa** [mumuki/mumuki-bash-runner#13]
I don't now why `mkdir` and `ls` returns `command not foud`

With `touch` command fails too...
`pwd` and `echo` works fine.
I don't test it with other commands.

![image](https://user-images.githubusercontent.com/1039278/31974278-3875a518-b901-11e7-8779-ac66fdff105e.png)

**Comment by flbulgarelli** [comment]
Can't reproduce anymore.
