### ISSUE TITLE
Cuando en el commit pones un espacio no anda

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-bash-runner#20]
![image](https://user-images.githubusercontent.com/11671943/42188995-9b0fa160-7e2c-11e8-9072-3e1cd25014f6.png)

https://sanluis.mumuki.io/exercises/4005-control-de-versiones-compartiendo-con-el-mundo-git-commit-git-push

**Comment by julian-berbel** [comment]
Probé crear un archivo con el contenido como lo forma el runner y obtengo el mismo resultado, por lo que el error parece ser de contenido, y no del runner en sí.

El contenido sería:
```
mkdir libro-maravilloso
cd libro-maravilloso
git init .
touch capitulo1.txt
echo "Había un avestruz." >> capitulo1.txt
git add capitulo1.txt
git remote add origin http://otra-pc/foo/bar
function git {
  STATUS=$(/usr/bin/git status)
  ACTION=$1
  REMOTE=$2
  BRANCH=$3
  [[ "$ACTION" == "push" ]] && [[ "$REMOTE" == "origin" ]] && [[ "$BRANCH" == "master" ]] && [[ $STATUS = *"nothing to commit"* ]] &&
  echo "El repositorio se actualizó correctamente" || /usr/bin/git $@
}
export -f git
cd /home/mumuki

cd libro-maravilloso
echo $?
git commit -m "asd 123"
``` 

Probando borrar la función git creada en el contenido extra, el commit funcionó sin problema, por lo que parece estar relacionado a eso.

**Comment by flbulgarelli** [comment]
OK, podrías corregir el contenido en cuestión, @julian-berbel ?

**Comment by julian-berbel** [comment]
Fixed. It was solved by wrapping the $@ in the git function in "s

Hell if I know why that fixes it, though.
