### ISSUE TITLE
Bash runner should support a list of commands as extra

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bash-runner#4]
For example, the following query: 

```json
{
  "extra": "mkdir foo\ncd foo\ntouch bar",
  "query": "ls"
}
```

should return `{"out": "bar", "status": "passed"}`

**Comment by julian-berbel** [comment]
Extra was added in comiple_file_content in d46fd4004586b50a5719bb9880f3ed497544ac04
